# Generated by Django 4.1.7 on 2023-03-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Creates.level'),
            preserve_default=False,
        ),
    ]
