# Generated by Django 4.1.7 on 2023-03-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creates', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='Name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
