# Generated by Django 4.1.7 on 2023-03-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('Creates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSchedul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=40)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creates.class')),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.day')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creates.class')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Creates.teacher')),
            ],
        ),
    ]
