# Generated by Django 4.1.7 on 2023-03-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('Creates', '0002_class_level'),
        ('ClassContent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_on', models.DateField(auto_now_add=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creates.class')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
