# Generated by Django 4.1.7 on 2023-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassContent', '0002_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekschedul',
            name='From',
            field=models.TimeField(default='1:11:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekschedul',
            name='To',
            field=models.TimeField(default='1:11:00'),
            preserve_default=False,
        ),
    ]
