# Generated by Django 4.1.7 on 2023-03-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('student', '0002_exammark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='Exam',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='Subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
