# Generated by Django 4.1.7 on 2023-03-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_examschedul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedul',
            name='From',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
        migrations.AlterField(
            model_name='examschedul',
            name='To',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
