# Generated by Django 4.1.7 on 2023-03-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creates', '0005_delete_notification'),
        ('subject', '0003_alter_examschedul_from_alter_examschedul_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedul',
            name='Level',
        ),
        migrations.AlterField(
            model_name='examschedul',
            name='From',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='examschedul',
            name='To',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creates.level')),
            ],
        ),
        migrations.AddField(
            model_name='examschedul',
            name='ExamName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subject.exam'),
            preserve_default=False,
        ),
    ]
