# Generated by Django 4.1.7 on 2023-03-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ClassContent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.TextField()),
                ('TeacherClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassContent.teacherclass')),
            ],
        ),
    ]
